### ISSUE TITLE
If you go to jail twice you never get out

### ISSUE THREAD

**Issue by lotvall** [wraithM17/lifely#3]
If you go to jail the first time and get sentenced to prison you get 36 months of jail time. The second time you get sent to prison it starts counting from 36/36 months of jail time served. And you never get released.

![Skärmavbild 2020-03-16 kl  01 49 23](https://user-images.githubusercontent.com/11683217/76714634-8111c680-6728-11ea-9734-63a52b649785.png)

**Comment by CarboxyDev** [comment]
Issue fixed. Thank you for reporting.

**Comment by lotvall** [comment]
No problem! Also, I thought it was a pretty fun game, keep up the awesome work! :)

I would suggest making actions "stackable", so you can e.g. go to the library 20 times with two click instead of having to click "library" -> "confirm", "library" -> "confirm" 20 times. 

Cheers
